=== verblera/sonnets/DTD,XML,XSLT-2ed/XML-ASSIGNMENT.dtd
<!ELEMENT document (start, author?, sonnet, end)>
<!ELEMENT start EMPTY>

<!--SECTION FOR GENERAL INFO ABOUT A SONNET AND ITS AUTHOR-->

<!--ID is an identifier for easier search
origin stands for origin of author/poem (!!adjective)
type stands for a type of sonnet (Shakespearean, Petrarchan, etc)
alternativeType stands if a user believes that a sonnet has charachteristics of  two sonnet types
-->
<!ATTLIST start id CDATA #REQUIRED origin CDATA  #IMPLIED 
type CDATA #REQUIRED alternativeType CDATA #IMPLIED>

<!--Information about author -->
<!ELEMENT author (name, yearsOfLife) >
<!ELEMENT name (firstName, namePreposition?, surname) >
<!ELEMENT firstName (#PCDATA)>
<!-- name prepositions such as von, de, of--> 
<!ELEMENT namePreposition (#PCDATA)>
<!ELEMENT surname (#PCDATA)>
<!ELEMENT yearsOfLife (yearOfBirth, yearOfDeath?)>
<!ELEMENT yearOfBirth (#PCDATA) >
<!ELEMENT yearOfDeath (#PCDATA) >

<!-- SECTION FOR A SONNET ITSELF-->

<!-- firstLine means that the sonnet's title is identicaltot the first line (no title)-->
<!ELEMENT sonnet ((title|firstLine), stanza+) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT firstLine (#PCDATA) >
<!ELEMENT stanza (br, line+) >

<!-- each stanza is separated with a blank line-->
<!ELEMENT br EMPTY >

<!-- quatrain = 4 lines in a stanza; terza = 3 lines, sestet = 6 lines, octave = 8, couplet=2 lines, 
typical division for different types of sonnets-->
<!ATTLIST br stanzaType (quatrain | terza | sestet | octave| couplet| notDefined) #REQUIRED>

<!-- each line can contain caesura (0 or 1), rhyme (0 or more), act(=predicate), actor (noun, who?) -->
<!ELEMENT line (#PCDATA| caesura| rhyme| actor| act)* >

<!-- caesura is a pause inside a line-->
<!ELEMENT caesura EMPTY>
<!ELEMENT actor (#PCDATA) >
<!ELEMENT act (#PCDATA) >
<!ELEMENT rhyme (#PCDATA) >

<!-- sort of rhyme is a scheme of rhymes' positions (for example, ABAB: 
the rhyme for the first line is in the third line, for the second in the fourth;),
and type is a way in which rhymes are placed between themselves: coupled : next to each other; enclosed: inside another rhyme, 
for more info look https://literarydevices.net/rhyme-scheme/
the recommended list might be extended-->
<!ATTLIST rhyme partOfSpeech CDATA #REQUIRED sort (a| b| c| d| e| f| g |notDefined) #REQUIRED
type (coupled| enclosed| notSpecified) #REQUIRED>
<!ELEMENT end EMPTY >

=== verblera/sonnets/DTD,XML,XSLT-3ed/2sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="3.xsl"?>
<document>
    <start id="5" origin= "French" type="Baudlairean"/>
    <author>
        <name>
            <firstName>Joachim</firstName>
            <namePreposition>Du</namePreposition>
            <surname>Bellay</surname>
        </name>
        <yearsOfLife>
            <yearOfBirth>1522</yearOfBirth>
            <yearOfDeath>1560</yearOfDeath>
        </yearsOfLife>
    </author>
    <sonnet>
        <firstLine>Ceux qui sont amoureux, leurs amours chanteront</firstLine>
        <stanza>
            <!-- in these lines, rhymes are verb and acts which cannoe be accepted by dtd-->
            <br stanzaType="quatrain"/>
            <line>Ceux <actor>qui </actor><act>sont </act>amoureux,<caesura/>lleurs <actor>amours </actor><rhyme partOfSpeech="verb" sort="a" type="enclosed">chanteront</rhyme></line>
            <line>Ceux <actor>qui </actor><act>aiment </act> l'honneur,<caesura/><act>chanteront</act>de la <rhyme partOfSpeech="noun" sort="b" type="enclosed">gloire</rhyme></line>
            <line>Ceux <actor>qui </actor><act>sont </act> près du roi,<caesura/><act>publieront </act>sa <rhyme partOfSpeech="noun" type="enclosed" sort="b">victoire</rhyme></line>
            <line>Ceux <actor>qui </actor><act>sont </act>courtisans, <caesura/>leurs  <actor>faveurs </actor><rhyme partOfSpeech="verb" sort="a" type="enclosed">vanteront</rhyme>,</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Ceux <actor>qui </actor><act>aiment</act> les arts,<caesura/>les sciences <rhyme partOfSpeech="verb" type="enclosed" sort="a"> diront</rhyme>,</line>
            <line>Ceux <actor>qui </actor><act>sont</act> vertueux,<caesura/>pour tels se <act>feront </act><rhyme partOfSpeech="verb" sort="b" type="enclosed">croire</rhyme></line>
            <line>Ceux <actor>qui </actor><act>aiment</act> le vin, <caesura/><act>deviseront </act> de <rhyme partOfSpeech="verb" sort="b" type="enclosed">boire</rhyme></line>
            <line>Ceux <actor>qui </actor><act>sont </act>de loisir,<caesura/>de fables <rhyme partOfSpeech="verb" type="enclosed" sort="a">écriront</rhyme>,</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Ceux <actor>qui </actor><act>sont </act>médisants, <caesura/>se <act>plairont </act>à <rhyme partOfSpeech="verb" sort="c" type="enclosed">médire</rhyme></line>
            <line>Ceux <actor>qui </actor><act>sont </act>moins fâcheux,<caesura/><act>diront </act>des mots pour <rhyme partOfSpeech="verb" type="enclosed" sort="c">rire</rhyme></line>
            <line>Ceux <actor>qui </actor><act>sont </act>plus vaillants,<caesura/> <act>vanteront</act> leur <rhyme partOfSpeech="noun" sort="d" type="enclosed">valeur</rhyme></line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Ceux <actor>qui </actor>se <act>plaisent </act>trop,<caesura/><act>chanteront</act> leur <rhyme partOfSpeech="noun" type="enclosed" sort="e">louange</rhyme></line>
            <line>Ceux <actor>qui </actor><act>veulent </act> <act>flatter</act>,<caesura/><act>feront</act>  d'un diable un<rhyme partOfSpeech="noun" sort="e" type="enclosed">ange</rhyme></line>
            <line>Moi, <actor>qui</actor> <act>suis</act> malheureux,<caesura/><actor>je </actor><act>plaindrai </act>mon <rhyme partOfSpeech="noun" type="enclosed" sort="d">malheur</rhyme>.</line>
        </stanza>
    </sonnet>
    <end/>
</document>

=== verblera/sonnets/DTD,XML,XSLT-2ed/4sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="2.xsl"?>
<document>
    <start id="61" origin= "French" type="Baudelairean"/>
    <author>
        <name>
            <firstName>Joachim</firstName>
            <namePreposition>Du</namePreposition>
            <surname>Bellay</surname>
        </name>
        <yearsOfLife>
            <yearOfBirth>1522</yearOfBirth>
            <yearOfDeath>1560</yearOfDeath>
        </yearsOfLife>
    </author>
    <sonnet>
        <firstLine>Qui est ami du coeur est ami de la bourse,</firstLine>
        <stanza>
            <br stanzaType="quatrain"/>
            <line><actor>Qui</actor><act> est </act>du coeur<caesura/><act> est </act>ami de la <rhyme partOfSpeech="noun" sort="a" type="enclosed">bourse</rhyme>,</line>
            <line><actor>Ce </actor><act>dira </act>quelque honnête <caesura/>et hardi <rhyme partOfSpeech="noun" sort="b" type="enclosed">demandeur</rhyme>,</line>
            <line><actor>Qui</actor> de l'argent d'autrui<caesura/> libéral <rhyme partOfSpeech="noun" sort="b" type="enclosed">dépendeur</rhyme></line>
            <line>Lui-même à l’hôpital <caesura/>s'en <act>va</act> toute la <rhyme partOfSpeech="noun" sort="a" type="enclosed">course</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Mais songe là-dessus<caesura/> <actor>qu’</actor>il n' <act>est</act> si vive <rhyme partOfSpeech="noun" type="enclosed" sort="a">source</rhyme></line>
            <line>Qu'<actor>on </actor>ne <act>puisse épuiser</act>,<caesura/>ni si riche <rhyme partOfSpeech="noun" sort="b" type="enclosed">prêteur</rhyme></line>
            <line><actor>Qui</actor> ne <act>puisse</act> à la fin <caesura/><act>devenir </act><rhyme partOfSpeech="noun" type="enclosed" sort="b">emprunteur</rhyme>,</line>
            <line>Ayant affaire à gens<caesura/><actor> qui </actor>n'<act>ont </act>point de <rhyme partOfSpeech="noun" sort="a" type="enclosed">ressource</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Gordes, si <actor>tu </actor><act>veux vivre </act><caesura/>heureusement <rhyme partOfSpeech="adjective" type="coupled" sort="c">romain</rhyme>,</line>
            <line><act>Sois </act>large de faveur,<caesura/>mais <act>garde</act> que ta <rhyme partOfSpeech="noun" sort="c" type="coupled">main</rhyme></line>
            <line>Ne <act>soit </act>à tous venants <caesura/> trop largement <rhyme partOfSpeech="participle" type="enclosed" sort="d">ouverte</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Par l'un <actor>on </actor><act>peut gagner</act><caesura/> même son <rhyme partOfSpeech="noun" sort="e" type="enclosed">ennemi</rhyme>,</line>
            <line>Par l’autre bien souvent<caesura/> on <act>perd</act> un bon <rhyme partOfSpeech="noun" sort="e" type="enclosed">ami</rhyme>,</line>
            <line>Et quand <actor>on</actor><act> perd</act> l'argent,<caesura/>c’<act>est</act> une double <rhyme partOfSpeech="noun" sort="d" type="enclosed">perte</rhyme>.</line>
        </stanza>
    </sonnet>
    <end/>
</document>

=== verblera/sonnets/DTD,XML,XSLT-2ed/3sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="2.xsl"?>
<document>
    <start id="1" origin= "French" type="Baudelairean"/>
    <author>
            <name>
                <firstName>Joachim</firstName>
                <namePreposition>Du</namePreposition>
                <surname>Bellay</surname>
            </name>
        <yearsOfLife>
            <yearOfBirth>1522</yearOfBirth>
            <yearOfDeath>1560</yearOfDeath>
        </yearsOfLife>
    </author>
    <sonnet>
        <firstLine>Heureux celui qui peut longtemps suivre la guerre</firstLine>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Heureux <actor>celui</actor><caesura/><actor> qui </actor><act>peut </act>longtemps<caesura/> suivre la <rhyme partOfSpeech="noun" sort="a" type="enclosed">guerre</rhyme></line>
            <line>Sans mort,<caesura/>ou sans blessure,<caesura/>ou sans longue <rhyme partOfSpeech="noun" sort="b" type="enclosed">prison</rhyme>!</line>
            <line>Heureux <actor>qui </actor>longuement <act>vit </act><caesura/>hors de sa <rhyme partOfSpeech="noun" type="enclosed" sort="b">maison</rhyme></line>
            <line>Sans dépendre son bien<caesura/> ou sans vendre sa<rhyme partOfSpeech="noun" sort="a" type="enclosed"> terre</rhyme>!</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Heureux <actor>qui</actor><act> peut </act>en cour<caesura/>quelque faveur <rhyme partOfSpeech="verb" type="enclosed" sort="a">acquerre</rhyme></line>
            <line>Sans crainte de l’envie<caesura/> ou de quelque <rhyme partOfSpeech="noun" sort="b" type="enclosed">traïson </rhyme>!</line>
            <line>Heureux <actor>qui</actor><act> peut</act> longtemps <caesura/> sans danger de <rhyme partOfSpeech="noun" type="enclosed" sort="b">poison</rhyme></line>
            <line><act>Jouir</act> d’un chapeau rouge <caesura/>ou des clefs de saint <rhyme partOfSpeech="noun" sort="a" type="enclosed">Pierre </rhyme>!</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Heureux <actor>qui </actor>sans péril <caesura/><act>peut </act>la mer <rhyme partOfSpeech="verb" type="coupled" sort="c">fréquenter </rhyme>!</line>
            <line>Heureux <actor>qui </actor>sans procès <caesura/>le palais <act>peut </act><rhyme partOfSpeech="verb" sort="c" type="coupled">hanter </rhyme>!</line>
            <line>Heureux <actor>qui </actor><act>peut</act> sans mal<caesura/><act> vivre </act>l’âge d’un <rhyme partOfSpeech="noun" type="enclosed" sort="d">homme </rhyme>!</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Heureux <actor>qui </actor>sans souci <caesura/><act>peut garder </act> son <rhyme partOfSpeech="noun" sort="e" type="enclosed">trésor</rhyme>,</line>
            <line>Sa femme sans soupçon,<caesura/>et plus heureux <rhyme partOfSpeech="adverb" type="enclosed" sort="e">encor</rhyme></line>
            <line><actor>Qui</actor><act>a pu </act> sans peler <caesura/><act>vivre</act> trois ans à <rhyme partOfSpeech="noun" sort="d" type="enclosed">Rome</rhyme>!</line>
        </stanza>
    </sonnet>
    <end/>
</document>

=== verblera/sonnets/DTD,XML,XSLT-3ed/1sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="3.xsl"?>
<document>
    <start id="31" origin= "French" type="Baudlairean"/>
    <author>
        <name>
            <firstName>Joachim</firstName>
            <namePreposition>Du</namePreposition>
            <surname>Bellay</surname>
        </name>
        <yearsOfLife>
            <yearOfBirth>1522</yearOfBirth>
            <yearOfDeath>1560</yearOfDeath>
        </yearsOfLife>
    </author>
    <sonnet>
        <firstLine>Heureux Qui Comme Ulysse</firstLine>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Heureux  <actor>qui</actor>, comme Ulysse, <caesura/> <act>a fait</act> un beau <rhyme partOfSpeech="noun" sort="a" type="enclosed">voyage</rhyme></line>
            <line>Ou comme cestuy-là <caesura/> <actor>qui </actor><act>conquit </act>la <rhyme partOfSpeech="noun" type="enclosed" sort="b">toison</rhyme></line>
            <line>Et puis <act>est retourné</act>,<caesura/>plein d’usage et <rhyme partOfSpeech="noun" sort="b" type="enclosed">raison</rhyme>,</line>
            <line><act>Vivre</act> entre ses parents<caesura/> le reste de son<rhyme partOfSpeech="noun" type="enclosed" sort="a">âge </rhyme>!</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Quand <act>reverrai</act>-<actor>je</actor>,hélas,<caesura/>de mon petit <rhyme partOfSpeech="noun" sort="a" type="enclosed">village</rhyme></line>
            <line><act>Fumer </act><actor>la cheminée</actor><caesura/> et en quelle <rhyme partOfSpeech="noun" type="enclosed" sort="b">saison</rhyme></line>
            <line> <act>Reverrai</act>-<actor>je</actor> le clos<caesura/> de ma pauvre <rhyme partOfSpeech="noun" type="enclosed" sort="b">maison</rhyme></line>
           <!-- davantage =and many more, a tricky part of speech to define -->
            <line><actor>Qui</actor> m’<act>est</act> une province,<caesura/>et beaucoup <rhyme partOfSpeech="pronoun" sort="a" type="enclosed">davantage</rhyme></line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <!-- in these two stanzas the actors are rhymed, and since the element cannot be declared as PCDATA or EMPTY, actors are missed -->
            <line>Plus me <act>plaît</act> le <actor> séjour </actor><caesura/>qu’<act>ont bâti </act>  mes <rhyme partOfSpeech="noun" type="coupled" sort="c">aïeux</rhyme></line>
            <line>Que des <actor>palais </actor>Romains <caesura/>le front <rhyme partOfSpeech="adjective" sort="c" type="coupled">audacieux</rhyme>,</line>
            <line>Plus que le <actor>marbre</actor> dur:<caesura/> me <act>plaît </act> l’<actor>ardoise</actor>  <rhyme partOfSpeech="adjective" type="enclosed" sort="d">fine</rhyme></line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Plus mon <actor>Loir</actor> gaulois,<caesura/> que le <actor>Tibre</actor> <rhyme partOfSpeech="adjective" sort="e" type="enclosed">latin</rhyme>,</line>
            <line>Plus mon petit <actor>Liré,</actor><caesura/> que le <actor>mont </actor><rhyme partOfSpeech="adjective" type="enclosed" sort="e">Palatin</rhyme>,</line>
            <line>Et plus que l’<actor>air</actor> marin <caesura/> <actor>la doulceur</actor><rhyme partOfSpeech="adjective" sort="d" type="enclosed"> angevine</rhyme>.</line>
        </stanza>
    </sonnet>
    <end/>
</document>

=== verblera/sonnets/DTD,XML,XSLT-2ed/7sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="2.xsl"?>
<document>
    <start id="130" origin= "English" type="Shakespearean"/>
    <author>
        <name>
            <firstName>William</firstName>
            <surname>Shakespeare</surname>
        </name>
        <yearsOfLife>
            <yearOfBirth>1564</yearOfBirth>
            <yearOfDeath>1616</yearOfDeath>
        </yearsOfLife>
    </author>
    
    <sonnet>
        <firstLine>My mistress' eyes are nothing like the sun</firstLine>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>My mistress' <actor>eyes </actor><act>are </act> nothing like the <rhyme partOfSpeech="noun" sort="a" type="enclosed">sun</rhyme>;</line>
            <line><actor>Colar  </actor> <act>is </act> far more red than her lips'  <rhyme partOfSpeech="noun" sort="b" type="enclosed">red</rhyme>;</line>
            <line>If  <actor>snow </actor> <act>be </act> white, why then her <actor>breasts </actor> <act>are</act><rhyme partOfSpeech="adjective" sort="a" type="enclosed">dun</rhyme>;</line>
            <line>If <actor>hairs </actor> <act> be </act> wires, black <actor>wires </actor> <act>grow </act>on her <rhyme partOfSpeech="noun" sort="b" type="enclosed">head</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line><actor>I </actor><act>have seen</act> roses damasked, red and <rhyme partOfSpeech="adjective" sort="c" type="enclosed">white</rhyme>,</line>
            <line>But no such roses <act>see </act>  <actor>I </actor> in her <rhyme partOfSpeech="noun" sort="d" type="enclosed">cheeks</rhyme>;</line>
            <line>And ins some perfumes <act>is </act> there more <rhyme partOfSpeech="noun" sort="c" type="enclosed">delight</rhyme></line>
            <line>Than in the breath <actor>that </actor>from my mistress <rhyme partOfSpeech="verb" sort="d" type="enclosed">reeks</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line><actor>I </actor> <act>love </act> to hear <actor>her </actor><act>speak </act>, yet well <actor>I </actor><rhyme partOfSpeech="verb" sort="e" type="enclosed">know</rhyme></line>
            <line>That <actor>music </actor> <act>hath </act>a far more pleasing<rhyme partOfSpeech="noun" sort="f" type="enclosed">sound</rhyme>;</line>
            <line><actor>I </actor><act>grant </act> <actor>I </actor>never <act>saw </act>a goddess <rhyme partOfSpeech="verb" sort="e" type="enclosed">go</rhyme>;</line>
            <line>My <actor>mistress</actor> when <actor>she </actor> <act>walks </act><act> treads </act>on the <rhyme partOfSpeech="sound" sort="f" type="enclosed">ground</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="couplet"/>
            <line>And yet, by heaven, <actor>I </actor><act>think</act> my love as <rhyme partOfSpeech="adjective" sort="g" type="coupled">rare</rhyme>,</line>
            <line>As any <actor>she </actor><act>belied</act> with false <rhyme partOfSpeech="verb" sort="g" type="coupled">compare</rhyme>.</line>
        </stanza>
    </sonnet>
    <end/>
</document>

=== verblera/sonnets/DTD,XML,XSLT-1ed/6sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="1.xsl"?>
<document>
    <start id="1" type="OneginStanza" origin="Russian"/>
    <author>
        <name>
            <firstName>Alexander</firstName>
            <surname>Pushkin</surname>
        </name>
        <yearsOfLife>
            <yearOfBirth>1799</yearOfBirth>
            <yearOfDeath>1837</yearOfDeath>
        </yearsOfLife>
    </author>
    <sonnet>
        <firstLine>Мой дядя самых честных правил...</firstLine>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>"Мой <actor>дядя </actor>самых честных <rhyme partOfSpeech="noun" sort="a" type="enclosed">правил</rhyme>,</line>
            <line>Когда не в шутку <rhyme partOfSpeech="verb" sort="b" type="enclosed">занемог</rhyme>,</line>
            <line><actor>Он</actor> уважать себя <rhyme partOfSpeech="veb" sort="a" type="enclosed">заставил</rhyme></line>
            <line>И лучше выдумать не <rhyme partOfSpeech="verb" sort="b" type="enclosed">мог</rhyme>.</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Его <actor>пример </actor>другим <rhyme partOfSpeech="noun" sort="c" type="coupled">наука</rhyme>;</line>
            <line>Но, боже мой, какая <rhyme partOfSpeech="noun" sort="c" type="coupled">скука</rhyme></line>
            <line>С больным <act>сидеть </act>и день, и <rhyme partOfSpeech="noun" sort="d" type="coupled">ночь</rhyme>,</line>
            <line>Не отходя ни шагу <rhyme partOfSpeech="adverb" sort="d" type="coupled">прочь</rhyme>!</line>
        </stanza>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Какое низкое <rhyme partOfSpeech="noun" sort="e" type="enclosed">коварсто</rhyme></line>
            <line>Полуживого <rhyme partOfSpeech="verb" sort="f" type="enclosed">забавлять</rhyme>,</line>
            <line>Ему подушки <rhyme partOfSpeech="verb" sort="f" type="enclosed">поправлять</rhyme>,</line>
            <line>Печально <act>подносить </act><rhyme partOfSpeech="noun" sort="e" type="enclosed">лекарство</rhyme>:</line>
        </stanza>
        <stanza>
            <br stanzaType="couplet"/>
            <line><act>Вздыхать </act>и <act>думать про </act><rhyme partOfSpeech="pronoun" sort="g" type="coupled">себя</rhyme>:</line>
            <line>Когда же <actor>черт </actor><act>возьмет </act><rhyme partOfSpeech="pronoun" sort="g" type="coupled">тебя</rhyme>!"</line>
        </stanza>
    </sonnet>
    <end/>
</document>

=== verblera/sonnets/DTD,XML,XSLT-3ed/5sonnet.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE document SYSTEM "file://ad.ucl.ac.uk/homee/yjmsvve/DesktopSettings/Desktop/15102238-INST0032/DTD,XML,XSLT-1ed/XML-ASSIGNMENT.dtd">
<?xml-stylesheet type="text/xsl" href="3.xsl"?>
<document>
    <start id="106" type="Baudelairean" origin="French"/>
    <author>
        <name>
            <firstName>Charles</firstName>
            <surname>Baudelaire</surname>
        </name>
        <yearsOfLife>
            <yearOfBirth>1821</yearOfBirth>
            <yearOfDeath>1867</yearOfDeath>
        </yearsOfLife>
    </author>
    
    <sonnet>
        <title>La Muse malade</title>
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Ma pauvre muse,  hélas! <caesura/> qu'<act>as</act>-<actor>tu</actor> donc ce <rhyme partOfSpeech="noun" sort="a" type="enclosed">matin</rhyme>?</line>
            <line>Tes <actor>yeux </actor> creux <act>sont peuplés </act><caesura/>de visions <rhyme partOfSpeech="adjective" sort="b" type="enclosed">nocturnes</rhyme>,</line>
            <line>Et <actor>je</actor> <act>vois </act>à tour <caesura/>réfléchis sur ton <rhyme partOfSpeech="noun" sort="a" type="enclosed">teint</rhyme></line>
            <line>La folie et l'horreur,<caesura/> froides et <rhyme partOfSpeech="adjective" sort="b" type="enclosed">taciturnes</rhyme>.</line>
        </stanza>
        
        <stanza>
            <br stanzaType="quatrain"/>
            <line>Le <actor>succube </actor>verdâtre <caesura/>et le <actor>rose</actor> <rhyme partOfSpeech="adjective" sort="a" type="enclosed">lutin</rhyme></line>
            <line>T'<act>ont</act>-<actor>ils</actor> <act>versé </act>la peur<caesura/> er l'amour de leurs <rhyme partOfSpeech="noun" sort="b" type="enclosed">urnes</rhyme>?</line>
            <line>Le <actor>cauchemar</actor>, <caesura/>d'un poing despotique et <rhyme partOfSpeech="adjective" sort="a" type="enclosed">mutin</rhyme></line>
            <line>T'<act>a</act>-t-<actor>il</actor> noyée au fond <caesura/>d'un fabuleux <rhyme partOfSpeech="noun" type="enclosed" sort="b">Minturnes</rhyme>?</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line><actor>Je</actor> <act>voudrais</act> qu'exhalant <caesura/> l'odeur de la <rhyme partOfSpeech="noun" sort="c" type="coupled">santé</rhyme></line>
            <line>Ton <actor>sein</actor> de pensers forts <caesura/><act>fût </act> toujours <rhyme partOfSpeech="participle" sort="c" type="coupled">fréquenté</rhyme>,</line>
            <line>Et que ton <actor> sang </actor>chrétien <caesura/><act>coulât </act>à flots <rhyme partOfSpeech="adjective" sort="d" type="coupled">rythmiques</rhyme>,</line>
        </stanza>
        <stanza>
            <br stanzaType="terza"/>
            <line>Comme les sons nombreux <caesura/>des syllabes <rhyme partOfSpeech="adjective" sort="d" type="coupled">antiques</rhyme>,</line>
            <line>Où règnent tour à tour<caesura/> le père des <rhyme partOfSpeech="noun" sort="e" type="coupled">chansons</rhyme>,</line>
            <line>Phoebus, et le grand Pan, <caesura/>le seigneur des <rhyme partOfSpeech="noun" sort="e" type="coupled">moissons</rhyme>.</line>
        </stanza>
    </sonnet>
    <end/>
</document>
